version: "3.9"
services: 
  web:
    container_name: "web"
    build: .
    ports: 
      - 8080:8080
  redis:
    container_name: "db"
    restart: always
    image: "redis:alpine"
    ports: 
      - 6379:6379
